// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeedyAirProj.Infrastructure.Context;

#nullable disable

namespace SpeedyAirProj.Migrations
{
    [DbContext(typeof(SpeedyAirDbContext))]
    [Migration("20241128195504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SpeedyAirProj.Core.Entities.Flight", b =>
                {
                    b.Property<int>("FlightNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arrival")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxesLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Departure")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightNumber");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightNumber = 1,
                            Arrival = 2,
                            BoxesLoaded = 0,
                            Capacity = 20,
                            Day = 1,
                            Departure = 1
                        },
                        new
                        {
                            FlightNumber = 2,
                            Arrival = 3,
                            BoxesLoaded = 0,
                            Capacity = 20,
                            Day = 1,
                            Departure = 1
                        },
                        new
                        {
                            FlightNumber = 3,
                            Arrival = 4,
                            BoxesLoaded = 0,
                            Capacity = 20,
                            Day = 1,
                            Departure = 1
                        },
                        new
                        {
                            FlightNumber = 4,
                            Arrival = 2,
                            BoxesLoaded = 0,
                            Capacity = 20,
                            Day = 2,
                            Departure = 1
                        },
                        new
                        {
                            FlightNumber = 5,
                            Arrival = 3,
                            BoxesLoaded = 0,
                            Capacity = 20,
                            Day = 2,
                            Departure = 1
                        },
                        new
                        {
                            FlightNumber = 6,
                            Arrival = 4,
                            BoxesLoaded = 0,
                            Capacity = 20,
                            Day = 2,
                            Departure = 1
                        });
                });

            modelBuilder.Entity("SpeedyAirProj.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Destination")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightNumber1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightNumber1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SpeedyAirProj.Core.Entities.Order", b =>
                {
                    b.HasOne("SpeedyAirProj.Core.Entities.Flight", "Flight")
                        .WithMany("Orders")
                        .HasForeignKey("FlightNumber1");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("SpeedyAirProj.Core.Entities.Flight", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
